### ISSUE TITLE
Errors on launch

### ISSUE THREAD

**Issue by mblom122** [Mila432/Summoners-War-Bot#1]
Hi I am getting some errors on launch:
Traceback (most recent call last):
File "C:\test\mycode.py", line 1, in 
from api import API
File "C:\test\api.py", line 70
print '[%s]:%s'%(time.strftime('%H:%M:%S'),msg)
                     ^
SyntaxError: invalid syntax

Are you using a different version then me or something?

**Comment by fnk93** [comment]
You probably have python 3. This is written in python 2

**Comment by mblom122** [comment]
Okay thanks, can I use phyton 2.7? Also what modules do I need to install for it?
