### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by Jessinra** [Mila432/Summoners-War-Bot#10]
can you please show how to use it? :) readme at least

and item_list = [9, 13], I can't find the mapping between the item and the number, 
how to do giant/dragon/ necro? how to set the monster ? does the result auto get or auto sold? 

can you provide some documentation, please ? 👍

**Comment by Jessinra** [comment]
does your code do dungeon using monster on defense ? since i saw:
unit_id_list = [{'unit_id': unit['unit_id']} for unit in
                        self.defense_unit_list]

**Comment by Jessinra** [comment]
really... please make a documentation about your masterpiece XD it will help tons people

**Comment by Mila432** [comment]
lol i was in bandung 2 weeks ago , no i am not that guy who makes documentations

**Comment by Jessinra** [comment]
Then who was the original author?
