### ISSUE TITLE
OPT KeyError: 'location'

### ISSUE THREAD

**Issue by oddessax** [Mila432/Summoners-War-Bot#14]
Ok still working through OTP issue; spent hours digging through code trying to follow the magic but can't see where its going amiss. Once of my accounts needs OTP and the other doesn't. This is the error that was featured on the other page.
```
...\Summoners-War-Bot-master\qpyou.py",` line 164, in hiveLogin
    sss = rr.headers['Location'].split('&')
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\requests\structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'
```

From what I can gather its having a heart attack over the fact that the OPT location variable cant be split etc... This is what the variable is 1 step before it breaks.
'Location': 'https://hub.qpyou.cn/index.php/../otp/main'

Now if I compare to the account that doesn't need otp I get the following variable passed for Location.
'Location': 'c2shub://login?error_code=0&uid=########&did=#########&sessionkey=################',

hoping this helps.

**Comment by Mila432** [comment]
i have this already fixed but i am still thinking about releasing it or not , something big is coming

**Comment by ronyse7** [comment]
Is it safe to use our did? I change did on qpyou.py with my did, and it's work

**Comment by oddessax** [comment]
ronyse7 I have no idea how changing you did worked unless it stopped the code from thinking you needed a OTP code all together; i changed mine and it didnt change the outcome at all.

**Comment by Mila432** [comment]
check this out 
https://forum.dbzdb.pw/topic/718-upcoming-summoners-war-web-bot/

**Comment by nuviaFox** [comment]
@oddessax you must change device information on qpyou.py

**Comment by oddessax** [comment]
@Mila432 I like the upcoming idea, actually saw you implement it on your other project. The thing i love about your platform now is I've been playing around with fairly aggressive rune optimizing and aggressive fodder farm/upgrade stuff. I was using other software that OCR's the device and because its closed source all I can do is make requests for features that I'd like and then need to wait for them to be developed/considered etc... I 100% support your decision to take the project whichever way you want but for me personally its the ability to work on these modules that would probably not be wanted by anyone else that holds value. Regardless, you've an amazing platform that still astounds me; how you've achieved what you have already is a credit to your skillset.

**Comment by Mila432** [comment]
Maybe I will publish the otp fix , and some other small fixes I found

**Comment by oddessax** [comment]
That would be amazing.
