### ISSUE TITLE
Need hive register function

### ISSUE THREAD

**Issue by laoli4121** [Mila432/Summoners-War-Bot#16]
I try to emulate the client working mechanism, looks like it do as below
1.  create a guest
2. do guest login
3. register hive    <====
4. link the hive account and the guest id data   <====
5. use hive login

In api.py we get 1,2,5
Is there a function to register hive account via the script? Or there's no way to get the user data which is created by api.py back to our client login.

**Comment by Mila432** [comment]
not an issue 
have the code ready submit a pull request
https://github.com/Mila432/Summoners-War-Bot/pulls
