### ISSUE TITLE
Guest create

### ISSUE THREAD

**Issue by doseonkim** [Mila432/Summoners-War-Bot#18]
creating uid from did using api: 'http://api.qpyou.cn/guest/create' now causes an error.

error_code: 1900

error_msg: This api is depcrecated

**Comment by Mila432** [comment]
Record this step and update the api

**Comment by doseonkim** [comment]
Hi, could I ask how you record this step because when I use Wireshark and use nox emulator using a proxy to my PC's local ip I don't get any http API calls to api.qpyou.cn for some reason. I do see the API calls to summoners war for guestlogin using the did/uid though, but not hive api calls unfortunately.

If you could provide any information, it would be extremely helpful. Thank you!

**Comment by ga-rude** [comment]
The deprecated api is probably the reason why hive login also no longer works, is it?
