### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by arey1124** [Mila432/Summoners-War-Bot#19]
I am unable to login and the error I get is : 

Traceback (most recent call last):
  File "mycode_hive.py", line 9, in <module>
    uid,did,sessionkey=QPYOU('236145028').hiveLogin(my_hivelogin,my_password)
  File "/Users/arihant/Downloads/swhack1111/qpyou.py", line 140, in hiveLogin
    if '/gdpr/login' in rr.headers['Location']:
  File "/Users/arihant/anaconda/lib/python2.7/site-packages/requests/structures.py", line 56, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'

**Comment by arey1124** [comment]
someone help please ?

**Comment by Mila432** [comment]
https://github.com/Mila432/Summoners-War-Bot/pull/21

**Comment by aceradryd** [comment]
The did "236145028" doesn't work anymore because I accidentally bound it to a wrong device (by repairing the API).

So you have to use another did, like "236145030".

**Comment by arey1124** [comment]
@aceradryd  I tried but still unable to login , same error

**Comment by aceradryd** [comment]
I see in your screenshot that you are still using the did "236145028". It doesn't work anymore, as I said before. You have to change it in your script against another one, such as "236145030".

**Comment by arey1124** [comment]
![screenshot 2018-11-11 at 10 04 49 pm](https://user-images.githubusercontent.com/9376072/48315561-d5210e00-e5fd-11e8-865c-99a0b7f5daaf.png)
@aceradryd  check this out

**Comment by aceradryd** [comment]
Ah, sorry. I assumed you were talking about the Guest_Login. This works again, but the hive login doesn't work as far as I know.

Do you absolutely need the registration with Hive?

**Comment by arey1124** [comment]
No I have an account , just wanna login with hive . Is it possible  ? @aceradryd @Mila432

**Comment by aceradryd** [comment]
At the moment no, because SW has changed the login procedure.
You can try to fix it on your own, if you want.

I have described here (#20) how you can access the relevant data.
