### ISSUE TITLE
Issue w/ repeatAreana()

### ISSUE THREAD

**Issue by Omtrw** [Mila432/Summoners-War-Bot#2]
a.repeatAreana()
  File "D:\Users\Adrien\Desktop\Summoners-War-Bot-master\api.py", line 527, in repeatAreana
    if wizard['defeat']==0 and wizard['wizard_level']<=limit:
UnboundLocalError: local variable 'limit' referenced before assignment

**Comment by thiefsnip3r** [comment]
I'm getting this all the sudden. Did you figure it out?
