### ISSUE TITLE
Recording API.

### ISSUE THREAD

**Issue by doseonkim** [Mila432/Summoners-War-Bot#20]
Hello, I'm having an issue with recording new API's with WireShark. When I try to record some HIVE API's, looking for the 'http://api.qpyou.cn/guest/create' or 'http://api.qpyou.cn/guest/auth' in WireShark, I never see it in the logs when I install Summoners War and run it for the first time (when it should be generating the uid from did?).

Do you mind telling me what step must be recorded in order to find the 'http://api.qpyou.cn/guest/create' step because I think I might be recording the wrong step.

Thank you very much for any information you could provide.

**Comment by aceradryd** [comment]
You have to use for example the mitmproxy from mitmproxy.org.
Install it on your computer, enter it in your mobile phone or in Nox as HTTP proxy (click on the active WLAN for a long time in the WLAN settings). Then go to  "mitm.it" on your mobile phone and install the certificate.
The last step is to set the proxy ignore_host settings to "^(?!(.+\.)*qpyou\.cn)(.)" (without quotation marks).

You can also simply start the proxy with the following command: mitmweb.exe --showhost -v --ignore-hosts ^(?!(.+\.)*qpyou\.cn)(.)

The filter is mandatory, because SW uses Appguard and Appguard uses Certificate Pinning.

**Comment by doseonkim** [comment]
Hey yeah thanks! I just tried it, indeed it records the API's sent out from Nox/mobile device. The only problem is, the results are similar to when I was using WireShark. I am able to see packets such as 'http://activeuser.qpyou.cn/gateway.php', but for some reason, I do not see the 'http://api.qpyou.cn/guest/create' usage at all and the game just starts somehow. I'm not sure if I'm recording the wrong step, but I thought this step occurred when we first install Summoners War and run it on our device as a guest.

**Comment by aceradryd** [comment]
You mean "https://api.qpyou.cn/guest/create", don't you? (SW uses at this site HTTPS not HTTP)

**Comment by doseonkim** [comment]
Yes that's what I mean, but I still don't see it being captured for some reason.

**Comment by aceradryd** [comment]
I just looked at it again in the program. You are right, the page is no longer called only registered and auth. But what I noticed is that the guest_uid is your HIVE-ID.

**Comment by doseonkim** [comment]
How did you manage to find registered and auth api calls because I don't get those either. 
I get to the "tap to start" in game and start the game and get into the in game name. 

If you are a guest, technically you have no hive_id, isn't that correct? So how would I manage to get hive-id for a guest account that has no email/hive id?

**Comment by aceradryd** [comment]
In the attached file are all the changes you need to make to repair the Guest_Login. But at the moment the uid is still needed as user input.

Unfortunately I don't have time to write a pull request at the moment. If you have time, you could do that. You may also be able to figure out when the uid will be created.

[changes.txt](https://github.com/Mila432/Summoners-War-Bot/files/2537915/changes.txt)

**Comment by doseonkim** [comment]
Yea, I got the workaround working as well a while back to make sure everything inside Summoners War content commands were working. 

I just needed to learn how to record the /guest/create API to generate the guest HIVE_ID/guest_uid with random did's. Still really don't have any idea how it's generated and how it's retrieved from HIVE before they login using the Guest_Login command for SW unfortunately...

I really appreciate your help though, guess I'm stuck at the same step. If you have the recording of 'guest/auth' step recorded, would it be too much to ask if you may share that packet with me? Curious as to what changed for that API because it did say that API was deprecated as well when I tested few weeks back.

**Comment by aceradryd** [comment]
I have found it!

It calls https://api.qpyou.cn/guest/generate
Request: FGYtHSe7K3FiPGgvIWWnd3BtHHIQ5X7th4898PqFQSxQ2Pu7cQdT/6YGWjHbfLLw0y3di3w2sA5SzcuJVczlUTmZzjbc42gIZNUFDiA+KGu+wKhG1+LyRhtouAuIVHujgGpT10D/R4lNI7EUjseRIlw/RlbdR2HNMqw/Ok5g8+XYLT+G7533PhrRvIs8kOCRlVuGPis3hgkc+pmYiTyEKs8NZ1t0e0lCYglQRUDAVO/zRz7yoFhRJQDtdOGXBmzfFxYyOrQFD6vobID0+00OD6uh0UL+xb/tDsPPBJSXyPx6cVV7vEwj6HW1VLukm9UbCiLGh3lIaSk67Jc0j1mXgg==
Response: {"type":"guest/generate", "error_code":0, "guest_uid":"90189802893", "did":"549308898"}

**Comment by doseonkim** [comment]
Oooh, I see! Thank you very much! That is good news! 

From what I'm seeing, it looks like..

They give us a RSA-512 bit key and a signature value. I'm guessing we are supposed to encrypt something using the key they give us and send that encrypted value to "guest/generate" and once they decrypt it successfully using their private key, they send a response of uid and did.

I'm just unsure of what we need to encrypt using the key they send us to successfully get a response back from them.

**Comment by aceradryd** [comment]
Okay, I have decrypted the request.

Request:
{"did":"549308898","appid":"com.com2us.smon.normal.freefull.google.kr.android.common","expire_time":"1541077472","hive_country":"DE","signature":"PfaZ7awVc&%%"}

The signature is the one from https://api.qpyou.cn/guest/key
Now we only have to implement a method to get the public key and the signature from https://api.qpyou.cn/guest/key
Then we have to encrypt the upper request (with our data) with the given public key and send it back.

**Comment by aceradryd** [comment]
Okay, I have implemented a method.
I will create a pull request now.

**Comment by doseonkim** [comment]
Nice! Out of curiosity how were you able to decrypt the message that we encrypt using the public key that HIVE has given to us?

**Comment by aceradryd** [comment]
The mitmproxy can intercept and alter the traffic. So I simply exchanged the public key for one of mine and then decrypted the following request.

**Comment by doseonkim** [comment]
Oh I see that's a very neat trick! 
And also what steps did you take in order to record the API call of 'guest/key' and 'guest/generate' because I never saw any of those calls being made when I installed it on Nox. I didn't even get to see 'guest/auth' api call.

**Comment by aceradryd** [comment]
I used the same options I mentioned above.

**Comment by DBa2016** [comment]
Hmmm... I had actually everything about Hive working early last year, so tried to make it work again - started with recording everything (really entire traffic) from my iPhone through a mitmproxy and removing obviously unrelated flows (facebook etc.).

So far, I found the following calls:

- GET http://summonerswar-eu.com2us.net/api/location_c2.php (a list of servers is returned, no cookies set; response is encrypted but decryptable)
- POST https://activeuser.qpyou.cn/gateway.php - this one already gives me some headache:
  - Some cookies are passed already with the request, which are not set anywhere, in particular "pmt_auth". Also, a field "REQ-AUTHKEY" is set in the request (in the response, too, but with a different value)
  - I cannot decrypt the request nor the response by the normal functions from smon_decryptor
- POST https://push.qpyou.cn/api/token_reg.php - less headache
  - again, the pmt_auth cookie (same value as for "activeuser.php")
  - request and response decryptable
  - "apns_token" is submitted in the json of the request body. No idea right now where this comes from.
- POST https://push.qpyou.cn/api/agree/v1/get.php - no headache except the pmt_auth cookie
- POST http://summonerswar-eu.qpyou.cn/api/server_status_c2.php - no headache except the pmt_auth cookie; the pmt_auth is present on all requests to the API from here on
- POST http://summonerswar-eu.qpyou.cn/api/version_info_c2.php - response has some version information, nothing really weird
- POST https://activeuser.qpyou.cn/gateway.php - again, same as before; cannot decrypt anything and see some weird cookies.
- POST https://api.qpyou.cn/device/registered - no headache, did is submitted via a cookie
- POST https://hub.qpyou.cn/auth - this seems a very important request:
  - some new cookies are sent to the server (wcs_bt, for example)
  - ci_session cookie is set in the response (and used in the request and response headers from now on)
  - returns HTTP302, redirecting to the next request
- GET https://hub.qpyou.cn/auth/recent_account - redirected  by a 302 from previous;
  - again a very important request, I think. Bunch of cookies are set, and this is also where "login_proc" is called from
- POST https://hub.qpyou.cn/auth/login_proc - the actual login. 
  - some cookies are set, and a redirect happens back to the app

Did anyone succeed in researching how pmt_auth gets generated? I think this is the major roadblock, everything else can be figured out.
