### ISSUE TITLE
Guest Login not working?

### ISSUE THREAD

**Issue by ga-rude** [Mila432/Summoners-War-Bot#28]
Glad to see you and this project are still alive :)

After cloning the repo, installing the dependencies and running mycode.py there still seems to exist an error with the guest login:

> uid:90174321082 did:236145028
> found infocsv:4.02.58_2PlaOH2o
> found proto_ver:11860
> failed to send data for GuestLogin
> Traceback (most recent call last):
>   File "mycode.py", line 15, in <module>
>     a.login()
>   File "/Summoners-War-Bot/api.py", line 473, in login
>     res= self.GuestLogin()
>   File "/Summoners-War-Bot/api.py", line 462, in GuestLogin
>     self.setUser(res)
>   File "/Summoners-War-Bot/api.py", line 447, in setUser
>     self.wizard_id=input['wizard_info']['wizard_id']
> TypeError: 'NoneType' object has no attribute '__getitem__'

Or am I missing something?

**Comment by Mila432** [comment]
public `qpyou.py` is very outdated com2us changed many things , my private one working fine

**Comment by matinhu** [comment]
> public `qpyou.py` is very outdated com2us changed many things , my private one working fine

any way to get access to this one? pm me

**Comment by arey1124** [comment]
@Mila432  How to access the private one? Any documentation or something?

**Comment by oddessax** [comment]
@Mila432 Any chance I can get a copy of qpyou.py? would be muchly appreciated

**Comment by SnarkSlayer** [comment]
@Mila432 Could I get a copy of qpyou.py as well? Thanks in advance

**Comment by arey1124** [comment]
@Mila432  can you please help? Please!
