### ISSUE TITLE
Dungeon not working

### ISSUE THREAD

**Issue by Omtrw** [Mila432/Summoners-War-Bot#3]
Always get "dont have battle data"

**Comment by Mila432** [comment]
what id you used?

**Comment by Omtrw** [comment]
Im using it like : a.doDungeon(5,10)
It have to the wrong way

**Comment by Omtrw** [comment]
From where did I have to take the id? 
Have same trouble with arena

**Comment by Omtrw** [comment]
closed

**Comment by arey1124** [comment]
@Omtrw  can you please let me know the dungeon id ?
