### ISSUE TITLE
Login page broken

### ISSUE THREAD

**Issue by arey1124** [Mila432/Summoners-War-Bot#30]
The URL - https://hub.qpyou.cn/auth is displaying the following error :

Service is unavailable due to a temporary error.

CODE : 5530

And it is showing login page broken error

**Comment by h20ray** [comment]
have you found to fix that?

**Comment by arey1124** [comment]
@Mila432  can you please help?

**Comment by arey1124** [comment]
@Mila432  I took the latest changes, still gives this error. Any idea why? Is there any steps I need to follow? Please help

**Comment by Mila432** [comment]
https://github.com/Mila432/Summoners-War-Bot/issues/28#issuecomment-814752566
