### ISSUE TITLE
ToA, Dungeon not working

### ISSUE THREAD

**Issue by ronyse7** [Mila432/Summoners-War-Bot#4]
Always said "don't have battle data"

**Comment by Mila432** [comment]
what id you used?

**Comment by ronyse7** [comment]
Is there specific id for dungeon and ToA? I don't know the ids

**Comment by Mila432** [comment]
yes
dungeons have xxxx ids
toa goes from 0 - 100

**Comment by ronyse7** [comment]
Can you give an example?

**Comment by ronyse7** [comment]
Please?

**Comment by ronyse7** [comment]
Still get "don't have battle data"

**Comment by Omtrw** [comment]
look at your PM on libre.io
