### ISSUE TITLE
error in login 

### ISSUE THREAD

**Issue by drdohh** [Mila432/Summoners-War-Bot#6]
only works with your own account, I tried with my several times and I checked my data, however, not enter. This error occurs.
http://prntscr.com/inqd74

**Comment by Omtrw** [comment]
did you change something in api.py?

**Comment by drdohh** [comment]
I just changed my login account and password from hive id

**Comment by Omtrw** [comment]
weird idk

**Comment by drdohh** [comment]
I edited the data by notepad, is there a problem?

**Comment by drdohh** [comment]
I downloaded the folder and changed the login ... through the notepad and then opened the file with python and gave this error

**Comment by Omtrw** [comment]
I edited with notepad++ and no issue

**Comment by drdohh** [comment]
ok I will see this

**Comment by drdohh** [comment]
oh no,I falied, your region is global?

**Comment by Omtrw** [comment]
nope eu

**Comment by drdohh** [comment]
ohhhh yeahhh men. This is it, man, I got it, the region was marked for Europe and my region is global, that's it, I've been trying to make it work for days

**Comment by drdohh** [comment]
How do I farm in faimon

**Comment by Omtrw** [comment]
Haha wp

**Comment by drdohh** [comment]
what codes do I change to farm in faimom

**Comment by Omtrw** [comment]
For xp?

**Comment by drdohh** [comment]
yes, I need to make other places, including dungeon light, water ...

**Comment by drdohh** [comment]
I want to do normal faimon, how can I do it with some code?

**Comment by Omtrw** [comment]
Idk how to farm faimon but here are the dungeon id:
8001=Giant
9001=Dragon
1001=monday elemental
2001=tuesday elemental
3001=wednesday elemental
4001=thursday elemental
5001=magic dungeon
7001=sunday elemental
6001=necro

**Comment by drdohh** [comment]
ok, I put those values ​​where, and how do I run this file so I can do other scenarios?

**Comment by Omtrw** [comment]
a.doMission(9,1,1) = faimon 1 stage normal difficulty
a.CompleteRegion(9,1) = complete faimon

**Comment by drdohh** [comment]
the a.CompleteRegion(9,1) = complete faimon command I need to put below a.doMission(9,1,1) = faimon 1 stage normal difficulty? since I was looking for and only found a command x at line 774 in apy.py

**Comment by Omtrw** [comment]
nop completeRegion is for all faimon and doMission 1 stage

**Comment by Omtrw** [comment]
you choose which one u want

**Comment by drdohh** [comment]
ok very thanks bro
