### ISSUE TITLE
Dungeon Not working

### ISSUE THREAD

**Issue by arey1124** [Mila432/Summoners-War-Bot#7]
I am unable to figure out the dungeon id syntax and how it works. Also how to set too hard difficulty? Please help.

**Comment by Omtrw** [comment]
Dungeon id list:
8001=Giant
9001=Dragon
1001=monday elemental
2001=tuesday elemental
3001=wednesday elemental
4001=thursday elemental
5001=magic dungeon
7001=sunday elemental
6001=necro

**Comment by arey1124** [comment]
what about difficulty of toa ?

**Comment by Omtrw** [comment]
1=normal
2=hard

**Comment by arey1124** [comment]
@Omtrw  I tried it but '2' doesnt work for hard

**Comment by Omtrw** [comment]
worked for me

**Comment by Omtrw** [comment]
like a.doTower(stage,difficulty)

**Comment by arey1124** [comment]
Okay i will try thanks :) @Omtrw

**Comment by Omtrw** [comment]
np ^^

**Comment by arey1124** [comment]
@Omtrw  is it possible to get banned account back ;(

**Comment by Omtrw** [comment]
haha nope, dont do things too obvious with your next account lmao

**Comment by Omtrw** [comment]
@arey1124 when doing ToA did you get the reward?

**Comment by arey1124** [comment]
@Omtrw  Yes

**Comment by arey1124** [comment]
@Omtrw  Its working fine. I hope there is some hack to unban the account :(

**Comment by Omtrw** [comment]
@arey1124 kk ty, dont think unban an account is possible, what lvl were you?

**Comment by arey1124** [comment]
@Omtrw  Level 50 and that account was three years of hard work :( I just used mod to test once. Thats it and banned ;(

**Comment by Omtrw** [comment]
@arey1124 wtf, im cheating since 6 months still not banned, did you finished ToA hard or something?

**Comment by arey1124** [comment]
@Omtrw Yes i finished toa hard , and I was conq in arena and i pushed into guardian

**Comment by Omtrw** [comment]
@arey1124 oh well ok, you've been just too greedy lmao

**Comment by arey1124** [comment]
@Omtrw  yes lol , but i just want help with it once :(

**Comment by Omtrw** [comment]
@arey1124 you were not able to do toa hard by your own?

**Comment by arey1124** [comment]
@Omtrw  I could do only upto toah 70

**Comment by Omtrw** [comment]
@arey1124 I think youve been banned because of arena, what 5nat did you lost?

**Comment by arey1124** [comment]
@Omtrw  light phoenix , two camilla , zaiross , praha , fire dragon knight and a lot more ;(

**Comment by Omtrw** [comment]
@arey1124 wow sad

**Comment by arey1124** [comment]
@Omtrw  yes !
