### ISSUE TITLE
Error 1401

### ISSUE THREAD

**Issue by mblom122** [Mila432/Summoners-War-Bot#8]
What does the error 1401 mean?

def create(self):
		res = json.loads(self.s.post('https://api.qpyou.cn/guest/create',data=self.p1).content)
		if res['error_code']==1401:
			if socket.gethostname()=='Admin-PC':
				return self.create()

I get that "ip banned" notice, every now and then when i make new guest accounts, do they ban ip for a few min or what is going on?

**Comment by fnk93** [comment]
Could be that they monitor the creation of guest accounts to limit the possible accounts being created in a few seconds from one ip.

**Comment by Mila432** [comment]
ye 5 acc -> ban there is a simple workaround for this , but i wont publish it as there is no reason why you would need 5+ accounts

**Comment by arey1124** [comment]
@Mila432  is there any possibility to get a banned account back ?
