### ISSUE TITLE
rewards for completions.

### ISSUE THREAD

**Issue by thiefsnip3r** [Mila432/Summoners-War-Bot#9]
Wondering if i'm missing something to auto-pick up the rune that comes with beating a mission/dungeon. Have TOA/dungeons/missions working perfectly but noticed i get no drops from them

**Comment by fnk93** [comment]
How did you notice?
Are you talking about the runes that drop at the end of dungeon runs or the ones from achievements etc.?

**Comment by thiefsnip3r** [comment]
At the end of dungeons or a world level. I had it run garen forest #3 on hard on a new account used my energy and I did not gain any runes

**Comment by fnk93** [comment]
Did it even drop a rune? How many runs have you tried?
You tried garen forest on hard? Did you unlock it first by finishing normal?

**Comment by thiefsnip3r** [comment]
I used a total of 80 energy (yes it was all unlocked I got the battle complete message in cmd) with no rune drop. Are you getting them?

**Comment by thiefsnip3r** [comment]
Tried it on new account- works flawlessly thanks again mila. I've built a complete mission list with notes and code lines for all tasks. If anyone wants msg me on libre
